import m5
from m5.objects import *
class CustomSimdFU(MinorFU):
    opClasses = minorMakeOpClassSet([
        "FloatAdd",
            "FloatCmp",
            "FloatCvt",
            "FloatMisc",
            "FloatMult",
            "FloatMultAcc",
            "FloatDiv",
            "FloatSqrt",
            "SimdAdd",
            "SimdAddAcc",
            "SimdAlu",
            "SimdCmp",
            "SimdCvt",
            "SimdMisc",
            "SimdMult",
            "SimdMultAcc",
            "SimdMatMultAcc",
            "SimdShift",
            "SimdShiftAcc",
            "SimdDiv",
            "SimdSqrt",
            "SimdFloatAdd",
            "SimdFloatAlu",
            "SimdFloatCmp",
            "SimdFloatCvt",
            "SimdFloatDiv",
            "SimdFloatMisc",
            "SimdFloatMult",
            "SimdFloatMultAcc",
            "SimdFloatMatMultAcc",
            "SimdFloatSqrt",
            "SimdReduceAdd",
            "SimdReduceAlu",
            "SimdReduceCmp",
            "SimdFloatReduceAdd",
            "SimdFloatReduceCmp",
            "SimdAes",
            "SimdAesMix",
            "SimdSha1Hash",
            "SimdSha1Hash2",
            "SimdSha256Hash",
            "SimdSha256Hash2",
            "SimdShaSigma2",
            "SimdShaSigma3",
            "Matrix",
            "MatrixMov",
            "MatrixOP",
            "SimdExt",
            "SimdFloatExt",
            "SimdFloatCvt",
            "SimdConfig",
            "SimdUnitStrideLoad",
            "SimdUnitStrideStore",
    ])
    opLat = 5
    issueLat = 2
    timings = [MinorFUTiming(description="SIMD FU", srcRegsRelativeLats=[3])]

class CustomFUPool(MinorFUPool):
    funcUnits = [
    MinorDefaultIntFU(),
    MinorDefaultIntFU(),
    MinorDefaultIntMulFU(),
    MinorDefaultIntDivFU(),
    MinorDefaultPredFU(),
    MinorDefaultMemFU(),
    MinorDefaultMemFU(),
    MinorDefaultMiscFU(),
    CustomSimdFU(),
]
    
